# Generated by Django 5.1.6 on 2025-02-20 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='mark',
            field=models.CharField(default='default value', max_length=255),
            preserve_default=False,
        ),
    ]
