# Generated by Django 5.1.6 on 2025-02-20 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_products_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='photo',
            field=models.ImageField(blank=True, default='products_default.png', null=True, upload_to='products/'),
        ),
    ]
