# Generated by Django 5.1.6 on 2025-03-12 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0004_alter_products_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='status',
            field=models.CharField(choices=[('indisponível', 'indisponível'), ('disponível', 'disponível')], default='disponível', max_length=50),
        ),
    ]
