# Generated by Django 5.1.6 on 2025-03-12 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0005_alter_products_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='photo',
            field=models.ImageField(blank=True, default='default_product.png', null=True, upload_to='products/'),
        ),
    ]
